#!/usr/bin/perl

use LWP::Simple;

my $currentpage = '';
my $i = 0;
my $interp = '';
my @args = '';

print "Looking For Group:\n";
$i = `ls *.gif | wc -l`;

while(true)
{
  $i++;
  $interp = sprintf("%04d", $i);
  $currentpage = get("http://www.lfgcomic.com/page/" . $i);
  if ($currentpage !~ /(uploads\/comics\/[^"]*)"/)
  {
    exit;
  }

  #print $interp;  
  #print $currentpage;
  #print $1 . " $i\n";
  print $interp . "\n";
  $discard = `wget http://newcdn.lfgcomic.com/$1 -O "lfg$interp.gif" 2> /dev/null`;
  $currentpage = '';
}
