#!/usr/bin/perl

use LWP::Simple;

my $currentpage = '';
my $i = 0;
my $interp = '';
my @args = '';

print "The Noob:\n";
$i = `ls *.jpg | wc -l`;

while(true)
{
  $i++;
  $interp = sprintf("%04d", $i);
  $currentpage = get("http://www.thenoobcomic.com/index.php?pos=" . $i);
  if ($currentpage !~ /(headquarters\/comics\/[A-Za-z0-9_]+\.jpg)/)
  {
    exit;
  }

  #print $interp;  
  #print $currentpage;
  #print $1 . " $i\n";
  print $interp . "\n";
  $discard = `wget http://www.thenoobcomic.com/$1 -O "noob$interp.jpg" 2> /dev/null`;
  $currentpage = '';
}
