#!/usr/bin/perl

use LWP::Simple;

my $currentpage = '';
my $i = 0;
my $interp = '';
my @args = '';

print "Fey Winds:\n";
$i = `ls *.jpg | wc -l`;

$archivepage = get("http://www.feywinds.com/archive/");
@skiplist = (214, 431);

while(true)
{
  $i++;
  $interp = sprintf("%04d", $i);
  if ($i ~~ @skiplist)
  {
    $discard = `touch fw$interp.jpg`;
    next;
  }

  if ($archivepage !~ /a href="([^"]*)">$i[^<]*<.a>/)
  {
    exit;
  }
  $comicurl = $1;
  $currentpage = get($comicurl);
  if ($currentpage !~ /og.image. content="([^"]*)"/)
  {
    exit;
  }

  #print $interp;  
  #print $currentpage;
  #print $1 . " $i\n";
  print $interp . "\n";
  $discard = `wget "$1" -O "fw$interp.jpg" 2> /dev/null`;
  system(@args); 
  $currentpage = '';
}
