#!/usr/bin/perl

use LWP::Simple;

my $currentpage = '';
my $i = 0;
my $interp = '';
my @args = '';

print "xkcd:\n";
$i = `ls *.png | wc -l`;

@skiplist = (404, 1608, 1663);

while(true)
{
  $i++;
  $interp = sprintf("%04d", $i);
  if ($i ~~ @skiplist)
  {
    print "Skipping $i\n";
    $discard = `touch xkcd$interp.png`;
    next;
  }

  $currentpage = get("http://xkcd.com/" . $i . "/");

  if ($currentpage !~ /imgs.xkcd.com\/comics\/([^"\n]*)"/)
  {
    exit;
  }

  $escaped = $1;
  print $interp . " - " . "http://imgs.xkcd.com/comics/$escaped" . "\n";
  $escaped =~ s/([^A-Za-z0-9_])/sprintf("%%%02X", ord($1))/seg; #urlencode match
  #print $interp;  
  #print $currentpage;
  #print $1 . " $i\n";
  $discard = `wget http://imgs.xkcd.com/comics/$escaped -O "xkcd$interp.png" 2> /dev/null`;
  $currentpage = '';
}
