#!/usr/bin/perl

use LWP::Simple;

my $currentpage = '';
my $i = 0;
my $interp = '';
my $interp2 = '';
my @args = '';
my $matched = '';
my $flag = '';

print "Girls With Slingshots:\n";
$i = `ls *.jpg | wc -l`;

while(true)
{
  $i++;
  $matched = '';
  $flag = '';
  if ($i > 9999)
  {
    exit;
  }
  $interp = sprintf("%04d", $i);
  $interp2 = sprintf("%03d", $i);
  $currentpage = get("http://www.girlswithslingshots.com/comic/gws-" . $i . "/");
  my $matchstring = "(comics\/[^.]*GWS" . $interp2 . "[^.]*\.jpg)";
  if ($currentpage !~ /$matchstring/)
  {
    $flag = 1;
  }

  $matched = $1;
  print "1 $matched\n";

  if ($flag == 1)
  {
    print "trying second\n";
    $currenttpage = '';
    $currentpage = get("http://www.girlswithslingshots.com/comic/gws" . $i . "/");
    #print $currentpage;
    if ($currentpage !~ /$matchstring/)
    {
      exit;
    }
    $matched = $1;
    print "2 $matched\n";
  }
  #print "3 $matched\n";  

  #print $interp;  
  #print $currentpage;
  print "File: " . $matched . " $i\n";
  print $interp . "\n";
  $discard = `curl http://www.girlswithslingshots.com/$matched -o "gws$interp.jpg" 2> /dev/null`;
  $currentpage = '';
  $matched = '';
}
