#!/bin/bash

filetype="jpg"
name="multiplex"

echo "Multiplex:"
i=`ls *.$filetype | wc -l`
while true;
do
  i=$(($i+1))
  if [ $i -ge 10000 ]; then
    break
  fi
  padded=`printf "%.3d" $i`
  result=`wget "http://www.multiplexcomic.com/images/strips/multiplex-$padded.png" -O "$name$padded.$filetype" 2>&1 | grep "16065"`
  if [ "x`file $name$padded.$filetype | grep HTML`" != "x" ];
  then
    rm $name$padded.$filetype
    break
  fi
  echo "$padded"
done 
