#!/bin/bash

filetype="jpg"
name="multiplex"

echo "Multiplex:"
i=`ls *.$filetype | wc -l`

while true;
do
  i=$(($i+1))
  if [ $i -ge 10000 ]; then
    break
  fi
  padded=`printf "%.3d" $i`
  wget "http://www.multiplexcomic.com/images/strips/multiplex-$padded.png" -O "$name$padded.$filetype" > /dev/null 2>&1

  if [ "x`file $name$padded.$filetype | grep '\(HTML\|empty\)'`" != "x" ];
  then
    rm $name$padded.$filetype
    wget "http://img.multiplex10.com/strips/multiplex-$padded.jpg" -O "$name$padded.$filetype" > /dev/null 2>&1
    if [ "x`file $name$padded.$filetype | grep '\(HTML\|empty\)'`" != "x" ];
    then
      rm $name$padded.$filetype
      break
    fi
  fi
  echo "$padded"
done
