#!/bin/bash

echo "Winters in Lavelle:"
i=`ls *.jpg | wc -l`
while true;
do
  i=$(($i+1))
  if [ $i -ge 10000 ]; then
    break
  fi
  padded=`printf "%.4d" $i`
  result=`wget "http://wintersinlavelle.com/img/comic/$i.jpg" -O "lavelle$padded.jpg" 2>&1 | grep "404 Not Found"`
  if [ "$result" != "" ]
  then
    rm lavelle$padded.jpg
    break
  fi
  echo "$padded"
done 
