#!/usr/bin/perl

use LWP::Simple;

my $currentpage = '';
my $i = 0;
my $interp = '';
my @args = '';

print "A Tale of Two Rulers:\n";
$i = `ls *.jpg | cut -c 1-13 | uniq | wc -l`;

while(true) {
  $i++;
  $interp = sprintf("%04d", $i);
  $currentpage = get("http://figmentforms.tumblr.com/post/139806271367/a-tale-of-two-rulers-archive-post");
  if ($currentpage !~ /href="([^"]*)"[^>]*>[^<]*65381;[^&<]*$i/) {
    exit;
  }

  $comicurl = $1;
  print "comicurl is " . $comicurl . "\n";
  $currentpage = get($comicurl);

  my @urls = ();
  while(1) {
    if ($currentpage =~ s/data-at2x="([^"]*)" alt="Part//i) {
      my $file = $1;
      push(@urls,$file) unless grep(/$file/, @urls);
    } else {
      last;
    }
  }

  if (scalar(@urls) == 0) {
    exit;
  }

  print "$interp\n";
  my $referer = "http://figmentforms.tumblr.com";
  for my $j (0 .. $#urls) {
    $jinterp = sprintf("%03d", $j + 1);
    $filename = "tworulers" . $interp . "_" . $jinterp . ".jpg";
    print $filename . "\n";
    print $urls[$j] . "\n";
    $discard = `wget '$urls[$j]' --referer "$referer" -O "$filename" 2> /dev/null`;
  }

  


  #print $interp;  
  #print $currentpage;
  #print $1 . " $i\n";
  $currentpage = '';
}
