#!/bin/bash

echo "Atland:"
i=`ls *.jpg | wc -l`
while true;
do
  i=$(($i+1))
  if [ $i -ge 10000 ]; then
    break
  fi
  padded=`printf "%.3d" $i`
  result=`wget "http://www.realmofatland.com/images/strips/atland$padded.jpg" -O "atland$padded.jpg" 2>&1 | grep "404 Not Found"`
  if [ "$result" != "" ]
  then
    rm atland$padded.jpg
    break
  fi
  echo "$padded"
done 
