#!/usr/bin/perl

#use LWP::Simple;
use LWP::UserAgent;

my $currentpage = '';
my $i = 0;
my $interp = '';
my @args = '';

print "TwoKinds:\n";
$i = `ls *.jpg | wc -l`;

while(true)
{
  $i++;
  if ($i > 10000) { exit; }
  $interp = sprintf("%04d", $i);
  my $ua = LWP::UserAgent->new;
  $ua->agent("Mozilla/5.0 (Ubuntu; X11; Linux x86_64; rv:9.0.1) Gecko/20100101 Firefox/9.0.1");
  $ua->timeout(10);

  $currentpage = $ua->get("http://twokinds.keenspot.com/comic/$i");
  if ($currentpage->decoded_content !~ /(comics\/[^.]*\.[a-z][a-z][a-z])[^>]*Comic Page[^>]*>/)
  {
    exit;
  }

  #print $interp;
  #print $currentpage;
  #print $1 . " $i\n";
  print $interp . "\n";
  $discard = `wget http://cdn.twokinds.keenspot.com/$1 -O "twokinds$interp.jpg" 2> /dev/null`;
  system(@args);
  $currentpage = '';
}

