#!/usr/bin/perl

use LWP::Simple;
use LWP::UserAgent;
use HTTP::Request;

my $currentpage = '';
my $i = 0;
my $interp = '';
my @args = '';

print "El Goonish Shive:\n";
$i = `ls *.gif | wc -l`;

while(true)
{
  $i++;
  $interp = sprintf("%04d", $i);
  #print "Attempting to get URL http://www.egscomics.com/index.php?id=" . $i . "\n";
  #Using the UserAgent thing because EGS blocks the useragent of LWP::Simple
  my $ua = LWP::UserAgent->new;
  $ua->agent("Mozilla/5.0 (Ubuntu; X11; Linux x86_64; rv:9.0.1) Gecko/20100101 Firefox/9.0.1");
  $ua->timeout(10);
  #my $req = HTTP::Request->new(GET => 'http://www.egscomics.com/');
  #$req->referer("http://www.egscomics.com/");
  $currentpage = $ua->get("http://www.egscomics.com/index.php?id=" . $i);
  #$currentpage = $ua->get('http://www.egscomics.com/');
  #print "currentpage is " . $currentpage->decoded_content . "\n";
  if ($currentpage->decoded_content !~ /title="[0-9]{4}-[0-9]{2}-[0-9]{2}" src="([^"]*)"/)
  {
    #print "Failed at $interp\n";
    exit;
  }

  #print $interp;  
  #print $currentpage;
  #print $1 . " $i\n";
  print $interp . "\n";
  $discard = `curl http://www.egscomics.com/$1 -o "egs$interp.gif" 2> /dev/null`;
  system(@args); 
  $currentpage = '';
}
