#!/usr/bin/perl

use LWP::Simple;

my $currentpage = '';
my $i = 0;
my $interp = '';
my @args = '';

print "Murphy's Law:\n";
$i = `ls *.jpg | wc -l`;

while(true)
{
  $i++;
  $interp = sprintf("%04d", $i);
  $currentpage = get("http://jenniferdrawscomics.com/murphys-law/murphys-law-$i/");
  if ($currentpage !~ /og:image" content="([^"]*)"/)
  { 
    exit;
  }

  #print $interp;  
  #print $currentpage;
  #print $1 . " $i\n";
  print $interp . "\n";
  $discard = `wget $1 -O "murphy$interp.jpg" 2> /dev/null`;
  system(@args); 
  $currentpage = '';
}
