#!/bin/bash

echo "Sequential Art:"
i=`ls *.jpg | wc -l`
while true;
do
  i=$(($i+1))
  if [ $i -ge 10000 ]; then
    break
  fi
  padded=`printf "%.4d" $i`
  result=`wget "http://www.collectedcurios.com/SA_${padded}_small.jpg" -O "SA$padded.jpg" 2>&1 | grep "404 Not Found"`
  if [ "$result" != "" ]
  then
    rm SA$padded.jpg
    break
  fi
  echo "$padded"
done 
