#!/usr/bin/perl

use LWP::Simple;

my $currentpage = '';
my $i = 0;
my $interp = '';
my @args = '';

print "Android Blues:\n";
$i = `ls *.jpg | wc -l`;

while(true)
{
  $i++;
  $interp = sprintf("%04d", $i);
  $archivepage = get("http://www.androidblues.com/?page_id=52");
  if ($archivepage !~ /a href="([^"]*)">Page $i<.a>/)
  {
    exit;
  }
  $currentpage = get($1);
  if ($currentpage !~ /class="comic">[^<]*<img [^>]*src="([^"]*)"/)
  {
    exit;
  }

  #print $interp;  
  #print $currentpage;
  #print $1 . " $i\n";
  print $interp . "\n";
  $discard = `wget $1 -O "ablues$interp.jpg" 2> /dev/null`;
  $currentpage = '';
}
